=== GanYakun/office-auto/applications/odata/documents/edmConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="ofbiz-edm">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="Action"/>
          <xs:element ref="ComplexType"/>
          <xs:element ref="EntityType"/>
          <xs:element ref="EnumType"/>
          <xs:element ref="Function"/>
        </xs:choice>
        <xs:element ref="EntityContainer"/>
      </xs:sequence>
      <xs:attribute name="ImportGlobal" use="required" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Action">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Parameter"/>
        <xs:element minOccurs="0" ref="ReturnType"/>
      </xs:sequence>
      <xs:attribute name="EntitySetPath" type="xs:NCName"/>
      <xs:attribute name="IsBound" type="xs:boolean"/>
      <xs:attribute name="IsService" type="xs:boolean"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="OfbizService"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ComplexType">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Property"/>
      </xs:sequence>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="OfbizClass"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="EntityType">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="Property"/>
          <xs:element ref="RelAlias"/>
        </xs:choice>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="NavigationProperty"/>
      </xs:sequence>
      <xs:attribute name="AttrDateEntityName" type="xs:NCName"/>
      <xs:attribute name="AttrEntityName" type="xs:NCName"/>
      <xs:attribute name="AttrNumericEntityName" type="xs:NCName"/>
      <xs:attribute name="AutoAnnotations" type="xs:boolean"/>
      <xs:attribute name="AutoProperties" type="xs:boolean"/>
      <xs:attribute name="BaseType" type="xs:NCName"/>
      <xs:attribute name="EntityCondition"/>
      <xs:attribute name="GroupBy" type="xs:boolean"/>
      <xs:attribute name="Handler" type="xs:anyURI"/>
      <xs:attribute name="LabelPrefix" type="xs:NCName"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="OfbizEntity" type="xs:NCName"/>
      <xs:attribute name="SearchOption"/>
      <xs:attribute name="hasDerivedEntity" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="RelAlias">
    <xs:complexType>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="Relations" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="NavigationProperty">
    <xs:complexType>
      <xs:attribute name="AutoBinding" type="xs:boolean"/>
      <xs:attribute name="ContainsTarget" type="xs:boolean"/>
      <xs:attribute name="CreateService" type="xs:NCName"/>
      <xs:attribute name="FilterByDate" type="xs:boolean"/>
      <xs:attribute name="Handler" type="xs:anyURI"/>
      <xs:attribute name="IsCollection" type="xs:boolean"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="Relations"/>
      <xs:attribute name="RemoveService" type="xs:NCName"/>
      <xs:attribute name="Type" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="EnumType">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Member"/>
      </xs:sequence>
      <xs:attribute name="EntityCondition"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="OfbizEntity" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Member">
    <xs:complexType>
      <xs:attribute name="Name" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="Value" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Function">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="Parameter"/>
        <xs:element ref="ReturnType"/>
      </xs:sequence>
      <xs:attribute name="IsBound" type="xs:boolean"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="OfbizService"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="EntityContainer">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded">
          <xs:element ref="EntitySet"/>
          <xs:element ref="ActionImport"/>
          <xs:element ref="FunctionImport"/>
          <xs:element ref="Singleton"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="EntitySet">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="NavigationPropertyBinding"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="Annotation"/>
      </xs:sequence>
      <xs:attribute name="EntityCondition"/>
      <xs:attribute name="EntityType" use="required" type="xs:NCName"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Annotation">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Record"/>
      </xs:sequence>
      <xs:attribute name="Term" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Record">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="PropertyValue"/>
      </xs:sequence>
      <xs:attribute name="Type" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PropertyValue">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="Collection"/>
      </xs:sequence>
      <xs:attribute name="Bool" type="xs:boolean"/>
      <xs:attribute name="Property" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Collection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="PropertyPath"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="PropertyPath" type="xs:NCName"/>
  <xs:element name="ActionImport">
    <xs:complexType>
      <xs:attribute name="Action" use="required" type="xs:NCName"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="FunctionImport">
    <xs:complexType>
      <xs:attribute name="Function" use="required" type="xs:NCName"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Singleton">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="NavigationPropertyBinding"/>
      </xs:sequence>
      <xs:attribute name="Handler" use="required"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="Type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Property">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="Text"/>
      </xs:sequence>
      <xs:attribute name="Field" type="xs:NCName"/>
      <xs:attribute name="IsAttribute" type="xs:boolean"/>
      <xs:attribute name="IsCollection" type="xs:boolean"/>
      <xs:attribute name="IsDateAttribute" type="xs:boolean"/>
      <xs:attribute name="IsNumericAttribute" type="xs:boolean"/>
      <xs:attribute name="Label" type="xs:NCName"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="Nullable" type="xs:boolean"/>
      <xs:attribute name="Precision" type="xs:integer"/>
      <xs:attribute name="RelAlias" type="xs:NCName"/>
      <xs:attribute name="Scale" type="xs:integer"/>
      <xs:attribute name="Type" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Text">
    <xs:complexType>
      <xs:attribute name="Path" use="required"/>
      <xs:attribute name="TextArrangement" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Parameter">
    <xs:complexType>
      <xs:attribute name="IsCollection" type="xs:boolean"/>
      <xs:attribute name="Name" use="required" type="xs:NCName"/>
      <xs:attribute name="Nullable" use="required" type="xs:boolean"/>
      <xs:attribute name="Precision" type="xs:integer"/>
      <xs:attribute name="Type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ReturnType">
    <xs:complexType>
      <xs:attribute name="IsCollection" type="xs:boolean"/>
      <xs:attribute name="Name" type="xs:NCName"/>
      <xs:attribute name="Type" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="NavigationPropertyBinding">
    <xs:complexType>
      <xs:attribute name="Path" use="required" type="xs:NCName"/>
      <xs:attribute name="Target" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== GanYakun/office-auto/config/paymentManageEdmConfig.xml
<ofbiz-edm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://dev.odatalab.com/dtds/edmconfig.xsd" ImportGlobal="false">    <!-- EntityType Party -->

    <EntityType Name="Payment" OfbizEntity="Payment"  AutoProperties="true"
        Handler="component://bf-demo/groovyScripts/paymentManage/Payment/generateEntityListFields.groovy"
                SearchOption="paymentId,StatusItem/description,ToParty/partyName,FromParty/partyName">
        <Property Name="statusId" >
            <ValueList CollectionPath="PaymentStatusItems" WithFixedValues="true" />
            <Text Path="StatusItem/description" TextArrangement="TextOnly" />
        </Property>
        <Property Name="paymentTypeId" >
            <Text Path="PaymentType/description" TextArrangement="TextOnly" />
        </Property>
        <Property Name="paymentMethodTypeId" >
            <Text Path="PaymentMethodType/description" TextArrangement="TextOnly" />
        </Property>

        <Property Name="partyIdFrom" >
            <Text Path="FromParty/partyName" TextArrangement="TextOnly" />
        </Property>
        <Property Name="partyIdTo" >
            <Text Path="ToParty/partyName" TextArrangement="TextOnly" />
        </Property>
        <Property Name="currencyUomId" >
            <Text Path="CurrencyUom/description" TextArrangement="TextOnly" />
        </Property>
        <Property Name="statusColor"  Type="numeric" Hidden="true" HiddenFilter="true"/>
<!--        <Property Name="chartCriticalValue"  Type="numeric" Hidden="true" HiddenFilter="true"/>-->
        <NavigationProperty Name="CurrencyUom" AutoBinding="true"  />
        <NavigationProperty Name="StatusItem" AutoBinding="true"  />
        <NavigationProperty Name="PaymentType" AutoBinding="true"  />
        <NavigationProperty Name="FromParty" AutoBinding="true" IsCollection="false"/>
        <NavigationProperty Name="ToParty" AutoBinding="true"  />
        <NavigationProperty Name="PaymentMethodType" AutoBinding="true"  />
        <NavigationProperty Name="OrderPaymentPreference" IsCollection="true"/>


        <NavigationProperty Name="InvoiceItem" Relations="AcctgTrans/Invoice/InvoiceItem" Type="InvoiceItem" IsCollection="true"/>
        <NavigationProperty Name="PaymentApplication" Type="PaymentApplication" IsCollection="true"  FilterByDate="false"/>
        <NavigationProperty Name="AcctgTrans" Type="AcctgTrans" IsCollection="true"  FilterByDate="false"/>
        <NavigationProperty Name="PaymentAttribute" Type="PaymentAttribute" IsCollection="true"  FilterByDate="false"/>
        <NavigationProperty Name="AcctgTransEntry" Type="AcctgTransEntry" IsCollection="true"  FilterByDate="false"
                            Relations="AcctgTrans/AcctgTransEntry"/>
        <HeaderInfo TypeName="支付" TypeNamePlural="支付列表">
            <Title Path="paymentId"/>
            <Description Path="comments"/>
        </HeaderInfo>

    </EntityType>

    <EntityType Name="OrderPaymentPreference" EntitySetName="OrderPaymentPreferences" AutoProperties="true" DraftEntityName="OrderPaymentPreferenceAppDraft"
                Handler="component://bf-demo/groovyScripts/purchaseOrderMange/OrderPaymentPreference/generateEntityListFields.groovy">

        <Property Name="orderPaymentStatus" Type="Edm.Int64"/>
        <Property Name="statusId" Immutable="true">
            <Text Path="PaymentStatusItem/description" TextArrangement="TextOnly"/>
        </Property>

        <NavigationProperty Name="OrderHeader" IsCollection="false"/>
        <NavigationProperty Name="FinAccount" IsCollection="false"/>
        <NavigationProperty Name="PaymentStatusItem" Relations="StatusItem" Type="PaymentStatusItem"/>
        <NavigationProperty Name="Uom" Relations="OrderHeader/Uom" Type="Uom"/>
        <NavigationProperty Name="FinAccount"/>
    </EntityType>

    <EntityType Name="FinAccount" AutoSet="true" EntitySetName="FinAccounts" AutoProperties="true" AttrEntityName="FinAccountAttribute">
        <Property Name="accountName" IsAttribute="true" Type="String"/>
        <Property Name="statusId">
            <Text Path="StatusItem/description" TextArrangement="TextOnly"/>
        </Property>

        <NavigationProperty Name="StatusItem"/>
    </EntityType>
    <EntityType Name="OrderHeader" AutoSet="true" EntitySetName="OrderHeaders" AutoProperties="true">
        <Property Name="statusId">
            <Text Path="StatusItem/description" TextArrangement="TextOnly"/>
        </Property>
        <NavigationProperty Name="StatusItem"/>
    </EntityType>

    <EntityType Name="PaymentStatusItem" OfbizEntity="StatusItem" EntitySetName="PaymentStatusItems" AutoProperties="true">
        <Property Name="statusId">
            <Text Path="description" TextArrangement="TextOnly"/>
        </Property>
    </EntityType>

    <EntityType Name="InvoiceItem" EntitySetName="InvoiceItems" AutoSet="true" AutoProperties="true">
        <Property Name="productId">
            <Text Path="Product/productName" TextArrangement="TextOnly"/>
        </Property>
        <NavigationProperty Name="InventoryItem" IsCollection="false"/>
        <NavigationProperty Name="Product" />
    </EntityType>

    <EntityType Name="InventoryItem" AutoProperties="true" EntitySetName="InventoryItems" AutoSet="true">
        <NavigationProperty Name="Product"/>
        <NavigationProperty Name="OwnerParty"/>

        <Property Name="productId">
            <Text Path="Product/productName" TextArrangement="TextOnly"/>
        </Property>
        <Property Name="ownerPartyId">
            <Text Path="OwnerParty/partyName" TextArrangement="TextOnly"/>
        </Property>
    </EntityType>

    <EntityType Name="Product" AutoSet="true" EntitySetName="Products" AutoProperties="true">
        <NavigationProperty Name="QuantityUom"/>
    </EntityType>

    <EntityType Name="AcctgTransEntry" AutoProperties="true" >
        
        <Property Name="currencyUomId" >
            <Text Path="CurrencyUom/description" TextArrangement="TextFirst" />
        </Property>
        <Property Name="glAccountTypeId" >
            <Text Path="GlAccountType/description" TextArrangement="TextOnly" />
        </Property>

        <NavigationProperty Name="AcctgTrans" Type="AcctgTrans"  FilterByDate="false"/>
        <NavigationProperty Name="GlAccountType"  FilterByDate="false"/>
        <NavigationProperty Name="CurrencyUom" AutoBinding="true"  />
        <NavigationProperty Name="GlAccountType"/>
        <NavigationProperty Name="GlAccount"/>
    </EntityType>

    <EntityType Name="AcctgTrans" AutoProperties="true" >
        
        
        <Property Name="acctgTransTypeId" >
            <Text Path="AcctgTransType/description" TextArrangement="TextOnly" />
        </Property>

        <NavigationProperty Name="AcctgTransType"  />
    </EntityType>

    <EntityType Name="PaymentApplication" AutoProperties="true" EntitySetName="PaymentApplications" AutoSet="true">
        <NavigationProperty Name="Payment"  />

    </EntityType>


    <EntityType Name="StatusItem" AutoProperties="true" >
        <Property Name="statusId">
            <Text Path="description" TextArrangement="TextOnly" />
        </Property>
    </EntityType>


    <EntityType Name="Party"  AutoProperties="true" AutoSet="true" EntitySetName="Parties">
        <NavigationProperty Name="PartyAndContact"/>
    </EntityType>
    <EntityType Name="PartyAndContact" AutoProperties="true" EntitySetName="PartyAndContacts" AutoSet="true"/>
    <EntityType Name="PaymentMethodType" AutoProperties="true" EntitySetName="PaymentMethodTypes" AutoSet="true"/>
    <EntityType Name="PaymentType" AutoProperties="true" EntitySetName="PaymentTypes" AutoSet="true"/>
    <EntityType Name="Uom" AutoProperties="true" EntitySetName="Unm" AutoSet="true"/>
    <EntityType Name="PaymentAttribute" AutoProperties="true" EntitySetName="PaymentAttributes" AutoSet="true"/>
    <EntityType Name="GlAccountType" AutoProperties="true" EntitySetName="GlAccountTypes" AutoSet="true"/>
    <EntityType Name="GlAccount" AutoProperties="true" EntitySetName="GlAccounts" AutoSet="true">
        <NavigationProperty Name="GlAccountClass"/>
        <Property Name="glAccountClassId">
            <Text Path="GlAccountClass/description" TextArrangement="TextOnly"/>
        </Property>
    </EntityType>
    <EntityType Name="GlAccountClass" AutoProperties="true" EntitySetName="GlAccountClasses" AutoSet="true"/>
    <EntityType Name="AcctgTransType" AutoProperties="true" EntitySetName="AcctgTransTypes" AutoSet="true"/>

    <EntityContainer>
        <EntitySet Name="Payments" EntityType="Payment" />
        <EntitySet Name="StatusItems" EntityType="StatusItem" />
        <EntitySet Name="AcctgTrans" EntityType="AcctgTrans" />
        <EntitySet Name="AcctgTransEntrys" EntityType="AcctgTransEntry" />
        <EntitySet Name="PaymentStatusItems" EntityType="StatusItem" EntityCondition="statusTypeId=PAYMENT_GENERAL_STATUS" />
    </EntityContainer>


</ofbiz-edm>

=== GanYakun/office-auto/config/launchpadManageEdmConfig.xml
<ofbiz-edm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://dev.odatalab.com/dtds/edmconfig.xsd" ImportGlobal="false">

    <!--  userLogin  -->
    <EntityType Name="PartyUserLogin" AutoProperties="true"
                Handler="component://officeauto/groovyScripts/launchpadManage/generateEntityListFields.groovy">
        <Property Name="ddFormType" Type="String"/>
        <NavigationProperty Name="Person" Type="Person" Relations="Party/Person"/>
        <NavigationProperty Name="PartyRole" Type="PartyRole" Relations="Party/PartyRole" IsCollection="true"/>
        <NavigationProperty Name="PartyGroup" Type="PartyGroup" Relations="Party/PartyGroup"/>
        <NavigationProperty Name="UILabApp" Type="UILabApp" Relations="Party/PartyRole/RoleType/RoleTypeUILabApp/UILabApp" IsCollection="true"/>
        <NavigationProperty Name="SecurityPermission" Type="SecurityPermission"
                            Relations="UserLoginSecurityGroup/SecurityGroupPermission/SecurityPermission" IsCollection="true"/>
        <NavigationProperty Name="RoleTypeSecurityPermission" Type="RoleTypeSecurityPermission"
                            Relations="Party/PartyRole/RoleType/RoleTypeSecurityPermission" IsCollection="true"/>
    </EntityType>
    <EntityType Name="Person" AutoProperties="true"/>
    <EntityType Name="PartyRole" AutoProperties="true"/>
    <EntityType Name="PartyGroup" AutoProperties="true"/>
    <EntityType Name="SecurityPermission" AutoProperties="true"/>
    <EntityType Name="UILabApp" AutoProperties="true"/>
    <EntityType Name="RoleTypeSecurityPermission" AutoProperties="true">
        <NavigationProperty Name="SecurityPermission"/>
    </EntityType>

    <EntityContainer>
        <Singleton Name="Me" Type="PartyUserLogin" Handler="com.dpbird.odata.SingletonHandler.getMe"/>
    </EntityContainer>
</ofbiz-edm>

=== GanYakun/office-auto/config/purchaseQuoteManageEdmConfig.xml
<ofbiz-edm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="https://dev.odatalab.com/dtds/edmconfig.xsd" ImportGlobal="false">

    <!--PurchaseQuote-->
    <EntityType Name="PurchaseQuote" OfbizEntity="Quote" EntityCondition="quoteTypeId=PURCHASE_QUOTE" EntitySetName="PurchaseQuotes" AutoProperties="true" AutoSet="true"
                Handler="component://bf-demo/groovyScripts/marketingSalesService/quote/generateEntityListFields.groovy">
        <LineItem>
            <DataField Values="quoteId,quoteName,partyId,custRequestId,salesChannelEnumId" Importance="High"/>
            <DataField Values="statusId" Criticality="statusColor" Importance="High"/>
            <Criticality Value="statusColor"/>
        </LineItem>

        <HeaderInfo TypeName="报价" TypeNamePlural="报价列表">
            <Title Path="quoteId"/>
            <Description Path="quoteName"/>
        </HeaderInfo>

        <FieldGroup Label="BaseInfo" Qualifier="BaseInfo">
            <DataField Values="partyId,salesChannelEnumId,custRequestId" Importance="High"/>
        </FieldGroup>

        <Property Name="partyId" ExcludeFromNavigationContext="true"/>

        <SelectionFields PropertyPath="quoteId,partyId,statusId"/>

        <Property Name="salesChannelEnumId">
            <Text Path="SalesChannelEnumeration/description" TextArrangement="TextOnly"/>
        </Property>
        <Property Name="statusId">
            <Text Path="QuoteStatusItem/description" TextArrangement="TextOnly"/>
            <ValueList CollectionPath="QuoteStatusItems" WithFixedValues="true"/>
        </Property>
        <Property Name="partyId">
            <Text Path="Supplier/partyName" TextArrangement="TextOnly"/>
            <ValueList CollectionPath="Suppliers"/>
        </Property>
        <Property Name="statusColor"  Type="numeric" Hidden="true" HiddenFilter="true"/>

        <NavigationProperty Name="QuoteStatusItem" Type="QuoteStatusItem" Relations="StatusItem"/>
        <NavigationProperty Name="SalesChannelEnumeration"/>
        <NavigationProperty Name="QuoteItem"/>
        <NavigationProperty Name="QuoteTerm"/>
        <NavigationProperty Name="Supplier" Type="Supplier" Relations="Party"/>
        <NavigationProperty Name="PurchaseRequest" Type="PurchaseRequest" Relations="CustRequest" IsCollection="false"/>
    </EntityType>

    <EntityType Name="QuoteTerm" AutoProperties="true" EntitySetName="QuoteTerms" AutoSet="true">
        <LineItem Qualifier="QuoteTermLineItem">
            <DataField Values="termTypeId,termValue,termDays,description,uomId" Importance="High"/>
        </LineItem>
        <Property Name="termTypeId">
            <Text Path="TermType/description" TextArrangement="TextOnly"/>
        </Property>
        <NavigationProperty Name="TermType"/>
    </EntityType>

    <EntityType Name="TermType" AutoProperties="true" AutoSet="true" EntitySetName="TermTypes">
        <Property Name="termTypeId">
            <Text Path="description" TextArrangement="TextOnly"/>
        </Property>
    </EntityType>

    <EntityType Name="Company" OfbizEntity="Party" AutoProperties="true" EntityCondition="PartyRole/roleTypeId=INTERNAL_ORGANIZATIO" EntitySetName="Companies" AutoSet="true">
        <Property Name="partyId">
            <Text Path="partyName" TextArrangement="TextOnly"/>
        </Property>
        <NavigationProperty Name="PartyAndContact"/>
        <NavigationProperty Name="PartyGroup"/>
    </EntityType>

    <EntityType Name="Supplier" OfbizEntity="Party" EntityCondition="PartyRole/roleTypeId=SUPPLIER" EntitySetName="Suppliers" AutoSet="true" AutoProperties="true">
        <Property Name="partyId" Label="供应商">
            <Text Path="partyName" TextArrangement="TextOnly"/>
        </Property>
        <NavigationProperty Name="PartyAndContact"/>
        <NavigationProperty Name="PartyGroup"/>
    </EntityType>

    <EntityType Name="PartyAndContact" AutoProperties="true" AutoSet="true" EntitySetName="PartyAndContacts"/>

    <EntityType Name="QuoteItem" AutoSet="true" EntitySetName="QuoteItems" AutoProperties="true">
        <LineItem Qualifier="QuoteItemLineItem">
            <DataField Values="productId,Product/productName,quantity,quoteUnitPrice,comments" Importance="High"/>
        </LineItem>

        <NavigationProperty Name="Product"/>
    </EntityType>

    <EntityType Name="PurchaseRequest" OfbizEntity="CustRequest" EntityCondition="custRequestTypeId=RF_PUR_QUOTE" AutoProperties="true" EntitySetName="PurchaseRequests" AutoSet="true">
        <Property Name="custRequestId">
            <Text Path="description" TextArrangement="TextOnly"/>
        </Property>
        <Property Name="fromPartyId">
            <Text Path="FromParty/partyName" TextArrangement="TextOnly"/>
        </Property>
        <NavigationProperty Name="FromParty"/>
    </EntityType>

    <EntityType Name="PartyGroup" AutoProperties="true" AutoSet="true" EntitySetName="PartyGroups"/>


    <EntityType Name="PartyAndContact" EntitySetName="PartyAndContacts" AutoProperties="true">
    </EntityType>

    <EntityType Name="Party" EntitySetName="Parties" AutoProperties="true" DraftEntityName="OrderPartyDraft">
        <Property Name="partyId">
            <Text Path="partyName" TextArrangement="TextOnly"/>
        </Property>
        <NavigationProperty Name="PartyAndContact"/>
    </EntityType>

    <EntityType Name="StatusItem" EntitySetName="OrderStatusItems" EntityCondition="statusTypeId=ORDER_STATUS" AutoProperties="true">
        <Property Name="statusId">
            <Text Path="description" TextArrangement="TextOnly"/>
        </Property>
        <ValueList CollectionPath="OrderStatusItems" WithFixedValues="true"/>
    </EntityType>

    <EntityType Name="Product" EntitySetName="Products" AutoProperties="true">
        <ValueList CollectionPath="Products" WithFixedValues="true"/>
        <Property Name="productId">
            <Text Path="productName" TextArrangement="TextOnly"/>
        </Property>
        <Property Name="productTypeId">
            <Text Path="ProductType/description" TextArrangement="TextOnly"/>
        </Property>
        <Property Name="quantityUomId" Label="单位">
            <Text Path="QuantityUom/description" TextArrangement="TextOnly"/>
        </Property>
        <NavigationProperty Name="ProductType"/>
        <NavigationProperty Name="QuantityUom"/>
    </EntityType>

    <EntityType Name="ProductType" EntitySetName="ProductType" AutoProperties="true">
    </EntityType>

    <EntityType Name="Uom"  EntitySetName="Uoms" AutoProperties="true"/>

    <EntityType Name="Enumeration" EntitySetName="OrderSalesEnumerations" EntityCondition="enumTypeId=ORDER_NEW_SALES_CHANNEL" AutoProperties="true">
        <ValueList CollectionPath="OrderSalesEnumerations" WithFixedValues="true" Label="选择销售渠道"/>
        <Property Name="enumId">
            <Text Path="description" TextArrangement="TextOnly"/>
        </Property>
    </EntityType>

    <EntityType Name="QuoteStatusItem" OfbizEntity="StatusItem" EntityCondition="statusTypeId=QUOTE_STATUS" AutoProperties="true" AutoSet="true" EntitySetName="QuoteStatusItems">
        <Property Name="statusId">
            <Text Path="description" TextArrangement="TextOnly"/>
        </Property>
    </EntityType>

    <EntityType Name="Enumeration" AutoProperties="true" EntityCondition="enumTypeId=ORDER_NEW_SALES_CHANNEL" EntitySetName="Enumerations" AutoSet="true">
        <Property Name="enumId">
            <Text Path="description" TextArrangement="TextOnly"/>
        </Property>
    </EntityType>

    <EntityContainer>
        <EntitySet Name="OrderStatusItems" EntityType="StatusItem" EntityCondition="statusTypeId=ORDER_STATUS"/>
        <EntitySet Name="CurrencyUoms" EntityType="Uom" EntityCondition="uomTypeId=CURRENCY_MEASURE"/>
        <!--=============================    ActionImportStart    =============================-->
        <ActionImport Name="DiscardAction" Action="DiscardAction"/>
        <!--=============================     ActionImportEnd    =============================-->
    </EntityContainer>
    <!--=====================================     CRUD Action definition Start   =====================================-->

    <Action Name="DiscardAction"/>
    <!--=====================================     CRUD Action definition End   =====================================-->


</ofbiz-edm>
